// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR_3c8yf40d5bSdt9HTzsb-TbJB_cDSC8',
    appId: '1:928284356376:web:88679e9f3d6d3de295f86d',
    messagingSenderId: '928284356376',
    projectId: 'dory-test-1d2ed',
    authDomain: 'dory-test-1d2ed.firebaseapp.com',
    storageBucket: 'dory-test-1d2ed.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWVPW8Wg55nGQ8FILQ-tNWxnid85VTzRQ',
    appId: '1:928284356376:android:1b21f8937b1836b795f86d',
    messagingSenderId: '928284356376',
    projectId: 'dory-test-1d2ed',
    storageBucket: 'dory-test-1d2ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz4fh_alk-DIpu_4dEGI9cdV-Giyl0DmI',
    appId: '1:928284356376:ios:e043aa9c8478c22b95f86d',
    messagingSenderId: '928284356376',
    projectId: 'dory-test-1d2ed',
    storageBucket: 'dory-test-1d2ed.firebasestorage.app',
    iosBundleId: 'com.example.dori',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz4fh_alk-DIpu_4dEGI9cdV-Giyl0DmI',
    appId: '1:928284356376:ios:e043aa9c8478c22b95f86d',
    messagingSenderId: '928284356376',
    projectId: 'dory-test-1d2ed',
    storageBucket: 'dory-test-1d2ed.firebasestorage.app',
    iosBundleId: 'com.example.dori',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCR_3c8yf40d5bSdt9HTzsb-TbJB_cDSC8',
    appId: '1:928284356376:web:d6891bb3999fe16295f86d',
    messagingSenderId: '928284356376',
    projectId: 'dory-test-1d2ed',
    authDomain: 'dory-test-1d2ed.firebaseapp.com',
    storageBucket: 'dory-test-1d2ed.firebasestorage.app',
  );
}
